FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# LightStore

Light is an API for minimalist storage managment. In particular, get the product details and define user ou can acces 
to the API.

# Group utilisateurs

## Users managment [/operators]

### Detail list of all users [GET]

Return all the users with all their informations except passwords .

+ Request
    + Headers

            Authorization: Basic ABC123

+ Response 200 (application/json)

        [
            {
                "IsPasswordDefined": false,
                "Login": "SuperAdmin",
                "Email": null,
                "FirstName": "Super",
                "Id": 1,
                "LastName": "Admin",
                "ModifiedDate": "2016-05-17T12:02:10.4730000"
            },
            {
                "IsPasswordDefined": false,
                "Login": "bledieu",
                "Email": "bledieu@tesfri.fr",
                "FirstName": "Baptiste",
                "Id": 2,
                "LastName": "Ledieu",
                "ModifiedDate": "2016-05-17T13:30:01.4170000"
            }
        ] 
        
+ Response 401
    + Headers

            WWW-Authenticate: Basic realm="protected"

### Create a new user [POST]

You can create a new user with a login, firstname, lastname and an optional email.


+ Request (application/json)
    + Headers

            Authorization: Basic ABC123

    + Body
    
            {
                "Login": "bledieu",
                "Email": "bledieu@tesfri.fr",
                "FirstName": "Baptiste",
                "LastName": "Ledieu",
            }

+ Response 201 (application/json)

    + Headers
    
            Location: /operators/2

    + Body
    
            {
                "IsPasswordDefined": false,
                "Login": "bledieu",
                "Email": "bledieu@tesfri.fr",
                "FirstName": "Baptiste",
                "Id": 2,
                "LastName": "Ledieu",
                "ModifiedDate": "2016-05-17T13:30:01.4170000"
            }
            
+ Response 401
    + Headers

            WWW-Authenticate: Basic realm="protected"
            
            
## Update a user [/operators/{user_id}]

+ Parameters
    + user_id: `2` (integer, required) - ID of the current user. 

### Update [PUT]

you can update the informations of a user excepted the login.

+ Request (application/json)
    + Headers

            Authorization: Basic ABC123
    + Body
    
            {
                "Email": "bledieu@tesfri.fr",
                "FirstName": "Baptiste",
                "LastName": "Ledieu",
            } 

+ Response 201 (application/json)

    + Headers

            Location: /operators/2

    + Body

            {
                "IsPasswordDefined": false,
                "Login": "bledieu",
                "Email": "bledieu@tesfri.fr",
                "FirstName": "Baptiste",
                "Id": 2,
                "LastName": "Ledieu",
                "ModifiedDate": "2016-05-17T13:30:01.4170000"
            }
# Group login

# LightStore Login

Login is a simple API allowing to know if operator should define its password during log on.

## Login [/login/{login}]

### Know if specified login should define its password [GET]
Response true if a valid typed login have to define its password during the first logon step.
+ Parameters
    + login: `bledieu` (string, required) - Operator login to use LightStore application.
        
+ Response 200 (text/plain)

        true