FORMAT: 1A
HOST: https://svr-grind.tesfri.intra:8084/

# LightStore

Light is an API for minimalist storage managment. In particular, get the product details and define operator ou can acces 
to the API.

# Group Operators

## General operation on Operators [/operators]

### Detail list of all Operators [GET]

Return all the operators with all their informations except passwords .

+ Request
    + Headers

            Authorization: Basic ABC123

+ Response 200 (application/json)

        [
            {
                "IsPasswordDefined": false,
                "Login": "SuperAdmin",
                "Email": null,
                "FirstName": "Super",
                "Id": 1,
                "LastName": "Admin",
                "ModifiedDate": "2016-05-17T12:02:10.4730000"
            },
            {
                "IsPasswordDefined": false,
                "Login": "bledieu",
                "Email": "bledieu@tesfri.fr",
                "FirstName": "Baptiste",
                "Id": 2,
                "LastName": "Ledieu",
                "ModifiedDate": "2016-05-17T13:30:01.4170000"
            }
        ] 
        
+ Response 401
    + Headers

            WWW-Authenticate: Basic realm="protected"

### Create a new operator [POST]

You can create a new operator with a login, firstname, lastname and an optional email.


+ Request (application/json)
    + Headers

            Authorization: Basic ABC123

    + Body
    
            {
                "Login": "bledieu",
                "Email": "bledieu@tesfri.fr",
                "FirstName": "Baptiste",
                "LastName": "Ledieu",
            }

+ Response 201 (application/json)

    + Headers
    
            Location: /operators/2

    + Body
    
            {
                "IsPasswordDefined": false,
                "Login": "bledieu",
                "Email": "bledieu@tesfri.fr",
                "FirstName": "Baptiste",
                "Id": 2,
                "LastName": "Ledieu",
                "ModifiedDate": "2016-05-17T13:30:01.4170000"
            }
            
+ Response 401
    + Headers

            WWW-Authenticate: Basic realm="protected"
            
            
## Manage an operator [/operators/{operator_id}]

+ Parameters
    + operator_id: `2` (integer, required) - ID of the current operator. 

### Update [PUT]

you can update the informations of an operator excepted the login.

+ Request (application/json)

    + Headers

            Authorization: Basic ABC123
    + Body
    
            {
                "Email": "bledieu@tesfri.fr",
                "FirstName": "Baptiste",
                "LastName": "Ledieu",
            } 

+ Response 201 (application/json)

    + Headers

            Location: /operators/2

    + Body

            {
                "IsPasswordDefined": false,
                "Login": "bledieu",
                "Email": "bledieu@tesfri.fr",
                "FirstName": "Baptiste",
                "Id": 2,
                "LastName": "Ledieu",
                "ModifiedDate": "2016-05-17T13:30:01.4170000"
            }
            
+ Response 401
    + Headers

            WWW-Authenticate: Basic realm="protected"
            
### Get operator details [GET]

you can get the informations of an operator excepted the password.

+ Request (application/json)

    + Headers

            Authorization: Basic ABC123
   

+ Response 201 (application/json)

    + Body

            {
                "IsPasswordDefined": false,
                "Login": "bledieu",
                "Email": "bledieu@tesfri.fr",
                "FirstName": "Baptiste",
                "Id": 2,
                "LastName": "Ledieu",
                "ModifiedDate": "2016-05-17T13:30:01.4170000"
            }
            
+ Response 401
    + Headers

            WWW-Authenticate: Basic realm="protected"

### Delete [DELETE]

you can delete an operator.

+ Request (application/json)

    + Headers

            Authorization: Basic ABC123
    

+ Response 204

+ Response 401
    + Headers

            WWW-Authenticate: Basic realm="protected"

# Group login

# LightStore Login

Login is a simple API allowing to know if operator should define its password during log on.

## Login [/login/{login}]

### Password defined [GET]
Response true if a valid typed login have to define its password during the first logon step.
+ Parameters
    + login: `bledieu` (string, required) - Operator login to use LightStore application.
        
+ Response 200 (text/plain)

        true